before

node.js:*
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
ReferenceError: foo is not defined
    at evalmachine.<anonymous>:*
    at *test/message/undefined_reference_in_new_context.js:*
    at Module._compile (node.js:*)
    at Object..js (node.js:*)
    at Module.load (node.js:*)
    at Array.<anonymous> (node.js:*)
    at EventEmitter._tickCallback (node.js:*)
